Update: text on preview stack
SwaprHQ/stackly-ui pull request #128
Opened 2023-10-27 18:53 UTC by Diogomartf

On the preview stack I think "worth" is confusing. People asked me what it meant, so I think "using" does a better job.

**now**
<img width="639" alt="image" src="https://github.com/SwaprHQ/stackly-ui/assets/5664434/1cc1e132-0e31-4d29-a790-67cbf41893ca">

**before**
<img width="718" alt="image" src="https://github.com/SwaprHQ/stackly-ui/assets/5664434/75529517-8681-4b9a-982d-62a459cc339d">

2023-10-30 12:50 UTC, ElRodrigote approved these changes

2023-10-30 14:37 UTC, berteotti approved these changes

2023-10-30 14:38 UTC, berteotti requested changes
Is it using the best words in this case?

2023-10-31 11:27 UTC, berteotti approved these changes
LGTM

2023-10-31 13:26 UTC, merged