fix: outline stroke on radio buttons should be lighter
SwaprHQ/stackly-ui pull request #60
Opened 2023-08-22 12:11 UTC by Diogomartf

<img width="627" alt="image" src="https://github.com/SwaprHQ/stackly-ui/assets/5664434/be72e0e0-bfe1-4337-a6c2-5bc8054a0ba5">

comments: https://web.ruttl.com/share/gWnw47S1jJZvzZcB4eez

2023-08-22 13:55 UTC, ElRodrigote submitted a review, later dismissed

2023-08-23 10:05 UTC, berteotti requested changes
I think this should be applied to every button, not only radio buttons

2023-08-23 10:13 UTC, Diogomartf commented
> I think this should be applied to every button, not only radio buttons

I think this is a bit out of scope of this PR, but as is it is just the ring, we can make them lighter on the buttons as well.

>

2023-08-23 10:32 UTC, berteotti approved these changes
LGTM. IMO Radio Buttons and Buttons shouldn't be different, except for the border radius. In my view Akash comments was made for every button.

2023-08-24 11:16 UTC, merged